dag:
  dag_id: 'TEST_MNTR_Produce_FlowNotifications'
  catchup: True
  concurrency: 1
  max_active_runs: 1
  schedule_interval: "0 */2 * * *"
  default_args:
    owner: 'azaparozhtsa'
    email: 'aliaksandr_zaparozhtsau@epam.com'
    dependsOnPast: False
    start_date: 2020-03-23T06:00:00Z
    end_date: 2050-03-23T06:00:00Z
    email_on_failure: True
    email_on_retry: True
    retries: 0
    retry_delay: 0
    provide_context: True

task_run_jar:
  jar_path: '/home/azaparozhtsa/flow_notifications/jars/flow_notifications.jar'
  main_path: 'com.burberry.monitoring.notifications.Main'
  global_config_path: '/home/azaparozhtsa/flow_notifications/global.conf'
