function res = v_mid(u, T, D, lambda, lambda_0, k, a, b, mu, t, tau, w)
    res = k * D ...
        * sigma_volna(D, k, a, b, mu, t, tau, w) ...
        * power(beta(T), 3) * power(w, 2) ...
        * u / 4 * sin(4*pi*(lambda-lambda_0));
end