# json_arr = '[{"key":"ga_session_id","value":{"value":null}},{"key":"ga_session_number","value":{"value":null}},{"key":"first_open_time","value":{"value":null}}]'
# json_arr = '[{"key":"firebase_conversion","value":{"string_value":null,"int_value":"1","float_value":null,"double_value":null}},{"key":"firebase_event_origin","value":{"string_value":"auto","int_value":null,"float_value":null,"double_value":null}},{"key":"ga_session_number","value":{"string_value":null,"int_value":"2","float_value":null,"double_value":null}},{"key":"session_engaged","value":{"string_value":null,"int_value":"1","float_value":null,"double_value":null}},{"key":"ga_session_id","value":{"string_value":null,"int_value":"1586543920","float_value":null,"double_value":null}},{"key":"engaged_session_event","value":{"string_value":null,"int_value":"1","float_value":null,"double_value":null}}]'
# json_arr = '[{"key":"firebase_event_origin","value":{"string_value":"app","int_value":null,"float_value":null,"double_value":null}},{"key":"ga_session_number","value":{"string_value":null,"int_value":"2","float_value":null,"double_value":null}},{"key":"CONTENT_TYPE","value":{"string_value":"CHAT_LIST","int_value":null,"float_value":null,"double_value":null}},{"key":"ga_session_id","value":{"string_value":null,"int_value":"1586543920","float_value":null,"double_value":null}},{"key":"engaged_session_event","value":{"string_value":null,"int_value":"1","float_value":null,"double_value":null}},{"key":"PAGE_TYPE","value":{"string_value":"CHAT_LIST","int_value":null,"float_value":null,"double_value":null}}]'
# json_arr = '[{"key":"firebase_event_origin","value":{"string_value":"auto","int_value":null,"float_value":null,"double_value":null}},{"key":"ga_session_number","value":{"string_value":null,"int_value":"2","float_value":null,"double_value":null}},{"key":"firebase_screen_id","value":{"string_value":null,"int_value":"-8572183267793968974","float_value":null,"double_value":null}},{"key":"entrances","value":{"string_value":null,"int_value":"1","float_value":null,"double_value":null}},{"key":"ga_session_id","value":{"string_value":null,"int_value":"1586543920","float_value":null,"double_value":null}},{"key":"firebase_screen_class","value":{"string_value":"ChatListViewController","int_value":null,"float_value":null,"double_value":null}},{"key":"engaged_session_event","value":{"string_value":null,"int_value":"1","float_value":null,"double_value":null}}]'
# json_arr = '[{"key":"firebase_event_origin","value":{"string_value":"app","int_value":null,"float_value":null,"double_value":null}},{"key":"ga_session_number","value":{"string_value":null,"int_value":"2","float_value":null,"double_value":null}},{"key":"firebase_screen_id","value":{"string_value":null,"int_value":"-8572183267793968974","float_value":null,"double_value":null}},{"key":"CONTENT_TYPE","value":{"string_value":"WELCOME_SCREEN","int_value":null,"float_value":null,"double_value":null}},{"key":"ga_session_id","value":{"string_value":null,"int_value":"1586543920","float_value":null,"double_value":null}},{"key":"firebase_screen_class","value":{"string_value":"ChatListViewController","int_value":null,"float_value":null,"double_value":null}},{"key":"engaged_session_event","value":{"string_value":null,"int_value":"1","float_value":null,"double_value":null}},{"key":"PAGE_TYPE","value":{"string_value":"WELCOME_SCREEN","int_value":null,"float_value":null,"double_value":null}}]'
# json_arr = '[{"key":"firebase_previous_id","value":{"string_value":null,"int_value":"-8572183267793968974","float_value":null,"double_value":null}},{"key":"firebase_event_origin","value":{"string_value":"auto","int_value":null,"float_value":null,"double_value":null}},{"key":"ga_session_number","value":{"string_value":null,"int_value":"2","float_value":null,"double_value":null}},{"key":"firebase_screen_id","value":{"string_value":null,"int_value":"-8572183267793968973","float_value":null,"double_value":null}},{"key":"firebase_previous_class","value":{"string_value":"ChatListViewController","int_value":null,"float_value":null,"double_value":null}},{"key":"ga_session_id","value":{"string_value":null,"int_value":"1586543920","float_value":null,"double_value":null}},{"key":"firebase_screen_class","value":{"string_value":"LoginViewController","int_value":null,"float_value":null,"double_value":null}},{"key":"engaged_session_event","value":{"string_value":null,"int_value":"1","float_value":null,"double_value":null}}]'
# json_arr = None

def test():
    json_arr = '[{"key":"firebase_event_origin","value":{"string_value":"auto","int_value":null,"float_value":null,"double_value":null}},{"key":"ga_session_number","value":{"string_value":null,"int_value":"2","float_value":null,"double_value":null}},{"key":"engagement_time_msec","value":{"string_value":null,"int_value":"278","float_value":null,"double_value":null}},{"key":"firebase_screen_id","value":{"string_value":null,"int_value":"-8572183267793968973","float_value":null,"double_value":null}},{"key":"ga_session_id","value":{"string_value":null,"int_value":"1586543920","float_value":null,"double_value":null}},{"key":"firebase_screen_class","value":{"string_value":"LoginViewController","int_value":null,"float_value":null,"double_value":null}},{"key":"engaged_session_event","value":{"string_value":null,"int_value":"1","float_value":null,"double_value":null}}]'
    import json
    res = json.loads(json_arr)

    for items in res:
        return str(items['value'])
        # if items['key'] == 'firebase_conversiыon':
        #     for i in items['valuыe']:
        #         if items['value'][i]:
        #             print('lol')
        #             print(items['value'][i])

v = test()

print(v)

